Models/Wedding.cs
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WeddingPlanner.Models;

public class Wedding
{
    [ Key ]
    [ Display( Name = "" ) ]
    public int WeddingId { get; set; }

    [ Required( ErrorMessage = "is required" ) ]
    [Display(Name = "Wedder One")]
    public string WedderOne { get; set; }

    [ Required( ErrorMessage = "is required" ) ]
    [ Display( Name = "Wedder Two" ) ]
    public string WedderTwo { get; set; }

    [ Required( ErrorMessage = "is required" ) ]
    [ Display( Name = "Date" ) ]
    [ DataType( DataType.Date ) ]
    [ FutureDate ]
    public DateTime Date { get; set; }

    [ Required( ErrorMessage = "is required" ) ]
    [ Display( Name = "Wedding Address" ) ]
    public string WeddingAddress { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;


    public int UserId { get; set; }
    public User? WeddingCreator { get; set; }
    public List<Attend> Guests { get; set; } = new List<Attend>();
    
}

Controllers/WeddingController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WeddingPlanner.Models;

namespace WeddingPlanner.Controllers;


public class WeddingController : Controller
{
    

    // _context is just a variable name, can be called anything (e.g. DATABASE, db, _db, etc)
    private WeddingPlannerContext _context;

    private int? uid
    {
        get
        {
            return HttpContext.Session.GetInt32("UUID");
        }
    }

    private bool loggedIn
    {
        get
        {
            return uid != null;
        }
    }

    // here we can "inject" our context service into the constructor
    public WeddingController( WeddingPlannerContext context )
    {
        _context = context;
    }

    [ HttpGet( "/wedding/dashboard" ) ]
    public IActionResult Dashboard()
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        List<Wedding> AllWeddings = _context.Weddings
        .Include( wedding => wedding.WeddingCreator )
        .Include( wedding => wedding.Guests )
        .ToList();

        return View( "Dashboard", AllWeddings );
    }

    [ HttpGet( "/wedding/new" ) ]
    public IActionResult New()
    {
        int? userId = HttpContext.Session.GetInt32("UUID");
        if (userId == null)
        {
            return RedirectToAction("Index", "User");
        }

        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        return View( "New" );
    }

    [ HttpPost( "/posts/create" ) ]
    public IActionResult Create( Wedding newWedding )
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        if (ModelState.IsValid == false) {
            // by not defaulting the return of View() in New, we can invoke the New() function & not have to re-write code
            // return View("New");

            return New();
        }

        if (uid != null)
        {
            newWedding.UserId = (int)uid;
        }

        _context.Weddings.Add( newWedding );
        _context.SaveChanges();

        return RedirectToAction( "Dashboard" );
    }

    [ HttpGet( "/weddings/{weddingId}" ) ]
    public IActionResult ViewWedding( int weddingId )
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        // since firstordefault can return a single post, or null. our variable needs to be a nullable datatype
        Wedding? wedding = _context.Weddings
            .Include( p => p.WeddingCreator )
            .Include( p => p.Guests )
            // .ThenInclude is used for including something on the
            // object that was JUST included (for this example, our likes list)
            .ThenInclude( p => p.User )
            .FirstOrDefault( p => p.WeddingId == weddingId );
        
        // to get rid of "object might be null" warnings, write a conditional that checks for it & returns if it's null
        if ( wedding == null )
        {
            return RedirectToAction( "Dashboard" );
        }
        
        return View( "ViewWedding", wedding );
    }

    [ HttpPost( "/weddings/{deletedWeddingId}/delete" ) ]
    public IActionResult Delete( int deletedWeddingId )
    {
        if (!loggedIn)
        {
            return RedirectToAction("Index", "User");
        }

        Wedding? weddingToBeDeleted = _context.Weddings.FirstOrDefault( wedding => wedding.WeddingId == deletedWeddingId );

        if (weddingToBeDeleted != null)
        {
            if(weddingToBeDeleted.UserId == uid)
            {
                _context.Weddings.Remove( weddingToBeDeleted );
                _context.SaveChanges();
            }
        }

        return RedirectToAction( "Dashboard" );
    }

    [ HttpPost( "/weddings/{weddingId}/rsvp" ) ]
    public IActionResult Rsvp( int weddingId )
    {
        if(!loggedIn || uid == null)
        {
            return RedirectToAction("Index", "User");
        }

        Attend? existingAttend = _context.Attends.FirstOrDefault( rsvp => rsvp.WeddingId == weddingId && rsvp.UserId == uid );

        if ( existingAttend == null )
        {
            Attend newAttend = new Attend(){
                WeddingId = weddingId,
                UserId = (int)uid
            };
            _context.Attends.Add( newAttend );
        }
        else
        {
            _context.Remove( existingAttend );
        }


        _context.SaveChanges();
        return RedirectToAction( "Dashboard" );
    }

}

Views/Wedding/Dashboard.cshtml
@model List<Wedding>

<h1>Welcome to the Wedding Planner</h1>

<table class="table table-striped">
<thead>
    <tr>
        <th scope="col"></th>
        <th scope="col">Wedding</th>
        <th scope="col">Date</th>
        <th scope="col">Guest</th>
        <th scope="col">Action</th>
    </tr>
</thead>
<tbody>
    @foreach( Wedding wedding in Model )
    {
        bool alreadyRSVP = wedding.Guests.Any( rsvp => rsvp.UserId == Context.Session.GetInt32("UUID") );
        <tr>
            <th scope="row"></th>
            <td><a asp-action="ViewWedding" asp-route-weddingId="@wedding.WeddingId">@wedding.WedderOne & @wedding.WedderTwo</a></td>
            <td>@wedding.Date</td>
            <td>@wedding.Guests.Count</td>
            <td>
                @if ( @wedding.WeddingCreator.UserId == Context.Session.GetInt32("UUID") )
                {
                    <a href="/weddings/@wedding.WeddingId/edit"><button>Edit</button></a>

                    <a
                        asp-controller="Wedding"
                        asp-action="Delete"
                        asp-route-deletedWeddingId="@wedding.WeddingId"
                        method="POST">
                            <button>Delete</button>
                    </a>

                }
                else
                {
                <form asp-controller="Wedding" asp-action="Rsvp" asp-route-weddingId="@wedding.WeddingId" method="post">
                    <button>
                        @if( alreadyRSVP )
                        {
                            <span>Un-RSVP</span>
                        }
                        else
                        {
                            <span>RSVP</span>
                        }
                    </button>
                </form>
                }
            </td>
        </tr>
    }
</tbody>
</table>


<a href="/wedding/new"><button>New Wedding</button></a>

Views/Wedding/New.cshtml
@model Wedding

<div class="container w-75 mx-auto">
    <h2 class="text-center">Plan Your Wedding</h2>


    <form class="shadow p-3 rounded" asp-controller="Wedding" asp-action="Create" method="POST">
        
        <label asp-for="WeddingId"></label>

        <div class="mb-3">
            <label asp-for="WedderOne"></label>
            <span asp-validation-for="WedderOne" class="text-danger font-weight-bold">
            </span>
            <input class="form-control" asp-for="WedderOne">
        </div>

        <div class="mb-3">
            <label asp-for="WedderTwo"></label>
            <span asp-validation-for="WedderTwo" class="text-danger font-weight-bold">
            </span>
            <input class="form-control" asp-for="WedderTwo">
        </div>

        <div class="mb-3">
            <label asp-for="Date"></label>
            <span asp-validation-for="Date" class="text-danger font-weight-bold">
            </span>
            <input type="date" class="form-control" asp-for="Date">
        </div>

        <div class="mb-3">
            <label asp-for="WeddingAddress"></label>
            <span asp-validation-for="WeddingAddress" class="text-danger font-weight-bold">
            </span>
            <input class="form-control" asp-for="WeddingAddress">
        </div>

        <button class="btn btn-success">Submit</button>
    </form>

</div>

Views/Wedding/ViewWedding.cshtml
@model Wedding

<h1>@Model.WedderOne and @Model.WedderTwo's Wedding</h1>

<h3>Date: @Model.Date</h3>

<p>Guests: </p>
<ul>
    @foreach( Attend guest in Model.Guests )
    {
        if( guest.User != null )
        {
            <li>@guest.User.FullName()</li>
        }
    }
</ul>